# Generated by Django 5.0.4 on 2024-04-22 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profile(apps, schema_editor):
    User = apps.get_model("auth", "User")
    ProfileModel = apps.get_model("api", "ProfileModel")
    for user in User.objects.all():
        ProfileModel.objects.create(user=user)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("avatar_url", models.CharField(blank=True, max_length=2048)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            create_profile, reverse_code=migrations.RunPython.noop, elidable=True
        ),
    ]
