/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SocialLoginSchema
 */
export interface SocialLoginSchema {
    /**
     * 
     * @type {string}
     * @memberof SocialLoginSchema
     */
    accessToken: string;
}

/**
 * Check if a given object implements the SocialLoginSchema interface.
 */
export function instanceOfSocialLoginSchema(value: object): boolean {
    if (!('accessToken' in value)) return false;
    return true;
}

export function SocialLoginSchemaFromJSON(json: any): SocialLoginSchema {
    return SocialLoginSchemaFromJSONTyped(json, false);
}

export function SocialLoginSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialLoginSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
    };
}

export function SocialLoginSchemaToJSON(value?: SocialLoginSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'access_token': value['accessToken'],
    };
}

